<?xml version="1.0" encoding="utf-8" ?>


<!--
   Copyright (C) Roman Arutyunyan
-->


<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">


<xsl:template match="/">
    <html>
        <head>
            <title>RTMP statistics</title>
            <style type="text/css">
                body {
                    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                    font-size: 13px;
                    color: #333;
                    background: #f5f5f5;
                    margin: 0;
                    padding: 16px;
                }
                a { color: #337ab7; text-decoration: none; }
                a:hover { text-decoration: underline; }

                table {
                    width: 100%;
                    border-collapse: collapse;
                    margin-bottom: 16px;
                    background: #fff;
                    box-shadow: 0 1px 3px rgba(0,0,0,.12);
                }
                th, td {
                    padding: 7px 10px;
                    text-align: left;
                    border-bottom: 1px solid #ddd;
                    vertical-align: top;
                }
                th {
                    font-weight: 600;
                    white-space: nowrap;
                    background: linear-gradient(to bottom, #5b9bd5 0%, #3a7abf 100%);
                    color: #fff;
                    border-bottom: 2px solid #2e6da4;
                }

                .row-global td  { background: #eaf2fb; }
                .row-app    td  { background: linear-gradient(to right, #d9edf7, #eaf4fb); font-weight: 600; }
                .row-section td { background: linear-gradient(to right, #e8e8e8, #f0f0f0); font-style: italic; }
                .row-stream-active  td { background: #fff; }
                .row-stream-idle    td { background: #fafafa; color: #999; }

                .badge {
                    display: inline-block;
                    padding: 2px 7px;
                    border-radius: 10px;
                    font-size: 11px;
                    font-weight: 600;
                    line-height: 1.4;
                    white-space: nowrap;
                }
                .badge-active    { background: #dff0d8; color: #3c763d; border: 1px solid #c3e6cb; }
                .badge-idle      { background: #f5f5f5; color: #777;    border: 1px solid #ddd; }
                .badge-pub       { background: #d9edf7; color: #31708f; border: 1px solid #bce8f1; }
                .badge-play      { background: #fcf8e3; color: #8a6d3b; border: 1px solid #faebcc; }
                .badge-relay     { background: #e8d5f5; color: #6a3d9a; border: 1px solid #d5a8f0; }
                .badge-autopush  { background: #fde8d8; color: #a0522d; border: 1px solid #f5c6a0; }
                .badge-exec      { background: #d4edda; color: #155724; border: 1px solid #b1dfbb; }
                .badge-dead      { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }

                .detail-row { display: none; }
                .detail-row td { background: #f9f9f9; padding: 10px; }

                .inner-table { width: auto; box-shadow: none; margin: 0; }
                .inner-table th {
                    background: linear-gradient(to bottom, #888, #666);
                    font-size: 12px;
                    padding: 4px 8px;
                }
                .inner-table td { font-size: 12px; padding: 4px 8px; background: #fff; }

                .exec-table { margin-top: 8px; }
                .exec-table th { background: linear-gradient(to bottom, #5cb85c, #4cae4c); }

                .footer {
                    font-size: 12px;
                    color: #888;
                    border-top: 1px solid #ddd;
                    padding-top: 10px;
                    margin-top: 8px;
                }
            </style>
        </head>
        <body>
            <xsl:apply-templates select="rtmp"/>
            <div class="footer">
                Generated by&#160;<a href="https://github.com/WoozyMasta/nginx-rtmp-module">nginx-rtmp-module</a>&#160;<xsl:value-of select="/rtmp/nginx_rtmp_version"/>,
                <a href="http://nginx.org">nginx</a>&#160;<xsl:value-of select="/rtmp/nginx_version"/>,
                pid&#160;<xsl:value-of select="/rtmp/pid"/>,
                built&#160;<xsl:value-of select="/rtmp/built"/>&#160;<xsl:value-of select="/rtmp/compiler"/>
            </div>
        </body>
    </html>
</xsl:template>


<xsl:template match="rtmp">
    <table>
        <tr>
            <th>RTMP</th>
            <th>#clients</th>
            <th colspan="4">Video</th>
            <th colspan="4">Audio</th>
            <th>In bytes</th>
            <th>Out bytes</th>
            <th>In bits/s</th>
            <th>Out bits/s</th>
            <th>State</th>
            <th>Time</th>
        </tr>
        <tr class="row-global">
            <td colspan="2">Accepted: <xsl:value-of select="naccepted"/></td>
            <th>codec</th>
            <th>bits/s</th>
            <th>size</th>
            <th>fps</th>
            <th>codec</th>
            <th>bits/s</th>
            <th>freq</th>
            <th>chan</th>
            <td>
                <xsl:call-template name="showsize">
                    <xsl:with-param name="size" select="bytes_in"/>
                </xsl:call-template>
            </td>
            <td>
                <xsl:call-template name="showsize">
                    <xsl:with-param name="size" select="bytes_out"/>
                </xsl:call-template>
            </td>
            <td>
                <xsl:call-template name="showsize">
                    <xsl:with-param name="size" select="bw_in"/>
                    <xsl:with-param name="bits" select="1"/>
                    <xsl:with-param name="persec" select="1"/>
                </xsl:call-template>
            </td>
            <td>
                <xsl:call-template name="showsize">
                    <xsl:with-param name="size" select="bw_out"/>
                    <xsl:with-param name="bits" select="1"/>
                    <xsl:with-param name="persec" select="1"/>
                </xsl:call-template>
            </td>
            <td/>
            <td>
                <xsl:call-template name="showtime">
                    <xsl:with-param name="time" select="/rtmp/uptime * 1000"/>
                </xsl:call-template>
            </td>
        </tr>
        <xsl:apply-templates select="server"/>
    </table>
</xsl:template>


<xsl:template match="server">
    <xsl:apply-templates select="application"/>
</xsl:template>


<xsl:template match="application">
    <tr class="row-app">
        <td colspan="16">
            <xsl:value-of select="name"/>
        </td>
    </tr>
    <xsl:apply-templates select="live"/>
    <xsl:apply-templates select="play"/>
</xsl:template>


<xsl:template match="live">
    <tr class="row-section">
        <td>live streams</td>
        <td><xsl:value-of select="nclients"/></td>
        <td colspan="14"/>
    </tr>
    <xsl:apply-templates select="stream"/>
</xsl:template>


<xsl:template match="play">
    <tr class="row-section">
        <td>vod streams</td>
        <td><xsl:value-of select="nclients"/></td>
        <td colspan="14"/>
    </tr>
    <xsl:apply-templates select="stream"/>
</xsl:template>


<xsl:template match="stream">
    <tr>
        <xsl:attribute name="class">
            <xsl:choose>
                <xsl:when test="active">row-stream-active</xsl:when>
                <xsl:otherwise>row-stream-idle</xsl:otherwise>
            </xsl:choose>
        </xsl:attribute>
        <td>
            <a href="">
                <xsl:attribute name="onclick">
                    var d=document.getElementById('<xsl:value-of select="../../name"/>-<xsl:value-of select="name"/>');
                    d.style.display=d.style.display=='none'?'':'none';
                    return false
                </xsl:attribute>
                <xsl:value-of select="name"/>
                <xsl:if test="string-length(name) = 0">
                    [EMPTY]
                </xsl:if>
            </a>
        </td>
        <td><xsl:value-of select="nclients"/></td>
        <td>
            <xsl:value-of select="meta/video/codec"/>&#160;<xsl:value-of select="meta/video/profile"/>&#160;<xsl:value-of select="meta/video/level"/>
        </td>
        <td>
            <xsl:call-template name="showsize">
                <xsl:with-param name="size" select="bw_video"/>
                <xsl:with-param name="bits" select="1"/>
                <xsl:with-param name="persec" select="1"/>
            </xsl:call-template>
        </td>
        <td>
            <xsl:apply-templates select="meta/video/width"/>
        </td>
        <td>
            <xsl:value-of select="meta/video/frame_rate"/>
        </td>
        <td>
            <xsl:value-of select="meta/audio/codec"/>&#160;<xsl:value-of select="meta/audio/profile"/>
        </td>
        <td>
            <xsl:call-template name="showsize">
                <xsl:with-param name="size" select="bw_audio"/>
                <xsl:with-param name="bits" select="1"/>
                <xsl:with-param name="persec" select="1"/>
            </xsl:call-template>
        </td>
        <td>
            <xsl:apply-templates select="meta/audio/sample_rate"/>
        </td>
        <td>
            <xsl:value-of select="meta/audio/channels"/>
        </td>
        <td>
            <xsl:call-template name="showsize">
                <xsl:with-param name="size" select="bytes_in"/>
            </xsl:call-template>
        </td>
        <td>
            <xsl:call-template name="showsize">
                <xsl:with-param name="size" select="bytes_out"/>
            </xsl:call-template>
        </td>
        <td>
            <xsl:call-template name="showsize">
                <xsl:with-param name="size" select="bw_in"/>
                <xsl:with-param name="bits" select="1"/>
                <xsl:with-param name="persec" select="1"/>
            </xsl:call-template>
        </td>
        <td>
            <xsl:call-template name="showsize">
                <xsl:with-param name="size" select="bw_out"/>
                <xsl:with-param name="bits" select="1"/>
                <xsl:with-param name="persec" select="1"/>
            </xsl:call-template>
        </td>
        <td><xsl:call-template name="streamstate"/></td>
        <td>
            <xsl:call-template name="showtime">
                <xsl:with-param name="time" select="time"/>
            </xsl:call-template>
        </td>
    </tr>
    <tr class="detail-row">
        <xsl:attribute name="id">
            <xsl:value-of select="../../name"/>-<xsl:value-of select="name"/>
        </xsl:attribute>
        <td colspan="16">
            <xsl:if test="client">
                <table class="inner-table">
                    <tr>
                        <th>Id</th>
                        <th>State</th>
                        <th>Address</th>
                        <th>Flash version</th>
                        <th>Page URL</th>
                        <th>SWF URL</th>
                        <th>Dropped</th>
                        <th>Timestamp</th>
                        <th>A-V</th>
                        <th>Time</th>
                    </tr>
                    <xsl:apply-templates select="client"/>
                </table>
            </xsl:if>
            <xsl:if test="dynamic_exec/proc">
                <table class="inner-table exec-table">
                    <tr>
                        <th>Exec arg</th>
                        <th>Command</th>
                        <th>PID</th>
                        <th>State</th>
                    </tr>
                    <xsl:for-each select="dynamic_exec/proc">
                        <tr>
                            <td><xsl:value-of select="arg"/></td>
                            <td><xsl:value-of select="cmd"/></td>
                            <td><xsl:value-of select="pid"/></td>
                            <td>
                                <xsl:choose>
                                    <xsl:when test="active">
                                        <span class="badge badge-exec">running</span>
                                    </xsl:when>
                                    <xsl:otherwise>
                                        <span class="badge badge-dead">exited</span>
                                    </xsl:otherwise>
                                </xsl:choose>
                            </td>
                        </tr>
                    </xsl:for-each>
                </table>
            </xsl:if>
        </td>
    </tr>
</xsl:template>


<xsl:template name="showtime">
    <xsl:param name="time"/>

    <xsl:if test="$time &gt; 0">
        <xsl:variable name="sec">
            <xsl:value-of select="floor($time div 1000)"/>
        </xsl:variable>

        <xsl:if test="$sec &gt;= 86400">
            <xsl:value-of select="floor($sec div 86400)"/>d
        </xsl:if>

        <xsl:if test="$sec &gt;= 3600">
            <xsl:value-of select="(floor($sec div 3600)) mod 24"/>h
        </xsl:if>

        <xsl:if test="$sec &gt;= 60">
            <xsl:value-of select="(floor($sec div 60)) mod 60"/>m
        </xsl:if>

        <xsl:value-of select="$sec mod 60"/>s
    </xsl:if>
</xsl:template>


<xsl:template name="showsize">
    <xsl:param name="size"/>
    <xsl:param name="bits" select="0"/>
    <xsl:param name="persec" select="0"/>
    <xsl:variable name="sizen">
        <xsl:value-of select="floor($size div 1024)"/>
    </xsl:variable>
    <xsl:choose>
        <xsl:when test="$sizen &gt;= 1073741824">
            <xsl:value-of select="format-number($sizen div 1073741824,'#.###')"/> T</xsl:when>
        <xsl:when test="$sizen &gt;= 1048576">
            <xsl:value-of select="format-number($sizen div 1048576,'#.###')"/> G</xsl:when>
        <xsl:when test="$sizen &gt;= 1024">
            <xsl:value-of select="format-number($sizen div 1024,'#.##')"/> M</xsl:when>
        <xsl:when test="$sizen &gt;= 0">
            <xsl:value-of select="$sizen"/> K</xsl:when>
    </xsl:choose>
    <xsl:if test="string-length($size) &gt; 0">
        <xsl:choose>
            <xsl:when test="$bits = 1">b</xsl:when>
            <xsl:otherwise>B</xsl:otherwise>
        </xsl:choose>
        <xsl:if test="$persec = 1">/s</xsl:if>
    </xsl:if>
</xsl:template>


<xsl:template name="streamstate">
    <xsl:choose>
        <xsl:when test="active">
            <span class="badge badge-active">active</span>
        </xsl:when>
        <xsl:otherwise>
            <span class="badge badge-idle">idle</span>
        </xsl:otherwise>
    </xsl:choose>
</xsl:template>


<xsl:template name="clientstate">
    <xsl:choose>
        <xsl:when test="publishing">
            <span class="badge badge-pub">publishing</span>
        </xsl:when>
        <xsl:otherwise>
            <span class="badge badge-play">playing</span>
        </xsl:otherwise>
    </xsl:choose>
    <xsl:if test="relay">
        &#160;<span class="badge badge-relay">relay</span>
    </xsl:if>
    <xsl:if test="auto_pushed">
        &#160;<span class="badge badge-autopush">auto-push</span>
    </xsl:if>
</xsl:template>


<xsl:template match="client">
    <tr>
        <td><xsl:value-of select="id"/></td>
        <td><xsl:call-template name="clientstate"/></td>
        <td>
            <a target="_blank">
                <xsl:attribute name="href">
                    http://apps.db.ripe.net/search/query.html&#63;searchtext=<xsl:value-of select="address"/>
                </xsl:attribute>
                <xsl:attribute name="title">whois</xsl:attribute>
                <xsl:value-of select="address"/>
            </a>
        </td>
        <td><xsl:value-of select="flashver"/></td>
        <td>
            <a target="_blank">
                <xsl:attribute name="href">
                    <xsl:value-of select="pageurl"/>
                </xsl:attribute>
                <xsl:value-of select="pageurl"/>
            </a>
        </td>
        <td><xsl:value-of select="swfurl"/></td>
        <td><xsl:value-of select="dropped"/></td>
        <td><xsl:value-of select="timestamp"/></td>
        <td><xsl:value-of select="avsync"/></td>
        <td>
            <xsl:call-template name="showtime">
                <xsl:with-param name="time" select="time"/>
            </xsl:call-template>
        </td>
    </tr>
</xsl:template>


<xsl:template match="width">
    <xsl:value-of select="."/>x<xsl:value-of select="../height"/>
</xsl:template>


</xsl:stylesheet>
